# Generated by Django 4.2.1 on 2024-05-24 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="blog_Catego",
            fields=[
                (
                    "cate_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Category ID",
                    ),
                ),
                ("cate_name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog_Post",
            fields=[
                (
                    "blog_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Blog ID",
                    ),
                ),
                (
                    "blog_Title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Title Name"
                    ),
                ),
                (
                    "blog_Category",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Blog Category",
                    ),
                ),
                (
                    "blog_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Text", "Text"),
                            ("Image", "Image"),
                            ("Video", "Video"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "blog_Post_Text",
                    models.TextField(
                        blank=True,
                        max_length=50000,
                        null=True,
                        verbose_name="Post Text",
                    ),
                ),
                (
                    "blog_file",
                    models.ImageField(
                        blank=True,
                        max_length=1000,
                        upload_to="Post/",
                        verbose_name="Post Image/Video",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created Date"
                    ),
                ),
                (
                    "blog_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment_Blog",
            fields=[
                (
                    "comment_pk",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Comment ID",
                    ),
                ),
                ("comment_type", models.CharField(blank=True, max_length=50)),
                (
                    "Comment_Text",
                    models.TextField(
                        blank=True,
                        max_length=10000,
                        null=True,
                        verbose_name="Comment Text",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created Date"
                    ),
                ),
                (
                    "comment_blog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeBlog.blog_post",
                    ),
                ),
                (
                    "comment_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="blog_Favorite",
            fields=[
                (
                    "fav_pk",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Favorite ID",
                    ),
                ),
                (
                    "fav_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fav_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeBlog.blog_post",
                    ),
                ),
            ],
        ),
    ]
