"""
Django settings for BlogNews project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import sys , os
from pathlib import Path 


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-y+4%xn)y%l*8h^^0vmtge=r)ul0b_^6s4y9g%vdj=5t^5vnjh&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",  

    "Accounts.apps.AccountsConfig", 
    'storeBlog.apps.StoreblogConfig',
    'storeBlog.templatetags', 
    
    'social_django',
]
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware", 

    "social_django.middleware.SocialAuthExceptionMiddleware",
]
SITE_ID = 2
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend', 
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE' : [
            'profile',
            'email'
        ], 
        'AUTH_PARAMS': {
            'access_type':'online',
        }
    }
}

LOGIN_REDIRECT_URL = '/blog/home/'
LOGOUT_REDIRECT_URL = '/account/logout/'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'your google cloud console key'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'your google cloud console secret key'




ROOT_URLCONF = "BlogNews.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ['Accounts/templates', 'storeBlog/templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
            ],
        },
    },
]

WSGI_APPLICATION = "BlogNews.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = False




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

#for google login

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'statics')
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'your email or username' # 'Hobby_Blog_News_Project.demo.django.login@gmail.com' 
EMAIL_HOST_PASSWORD = 'your password email'

VBcode = "http://localhost:8000/account"
LOCAL_HOST_STRIPE_Account = 'http://localhost:8000/account'
LOCAL_HOST_STRIPE_bloog = 'http://localhost:8000/blog'
LOCAL_HOST_STRIPE_VBcode = VBcode + '/logIn'


# ------------------ Stripe integration -------------------
STRIPE_PUBLIC_KEY = "**********84xqLsFylb0********************gwQifI696lrqejOacOFEV**********"
STRIPE_SECRET_KEY = "*****************QDUzRcd***************jbQxAau6bNtF097hPB*********************"
STRIPE_WEBHOOK_SECRET = "***************d956fc***********************48ba300**************4346b**********"



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = 'Accounts.UserProfile'
